[project]
version = "0.1.0"
name = "packages_from_git"
cincludes = []
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[variants]
default = []

[dependencies]
io = "1"

[repos]
extra = "git://github.com/zetzit/modules.git"
